# sites
title: "saadBi"
desctiption: "a Little Note"
url: "https://saadbi.github.io"
jobs: "GNU/Linux System Administrator - PHP"
permalink: ':title/'

markdown: kramdown
baseurl: "/"
full-version: "https://saadbi.github.io"

sass:
    style: compressed

# Authors
authors:
  fitri:
    name: "Fitri Ariyanto"
    display_name: masfitri
    email: seorang.fitri@gmail.com
    web: https://saadbi.github.io
    twitter: https://twitter.com/im_maskha
    description: "GNU/Linux system administrator."
  
#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge


# Tracker
analytics: UA-41637272-1

# Comments
disqus-shortname: saadbi

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

include: [_pages]
version: 0.8

plugins: 
    - jekyll-paginate
    - jekyll-seo-tag
    - jekyll-archives
